import React from "react";
 
const About = () => {
    return (
        <div>
            <h1>
                PlantGPT is a growing tool for planning and researching care instructions for your garden.
            </h1>
            <p>
              All plant care information is generated by OpenAI&#39s ChatGPT 3.5 and cannot be relied on for 100% accuracy.
            </p>
        </div>
    );
};
 
export default About;