import React from "react";

const Footer = () => {
  return (
    <div>
      <footer>
        <p>All plant data and plant images are generated by OpenAI and are not 100% reliable, for example the image of potatoes growing on a bush is inaccurate.</p>
      </footer>
    </div>
  );
};

export default Footer;